### Create a user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "afshan@college.edu",
  "password": "temp123",
  "role": "STUDENT"
}

### List all users
GET http://localhost:8080/api/users
